---
# tasks file for app
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Install ruby
  import_tasks: ruby.yml

- name: Install puma service
  import_tasks: puma.yml
